// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_server/protos.proto

package client_server;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SysOrBuilder extends
      // @@protoc_insertion_point(interface_extends:client_server.Sys)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .client_server.Person person = 1;</code>
     */
    java.util.List<client_server.Protos.Person> 
        getPersonList();
    /**
     * <code>repeated .client_server.Person person = 1;</code>
     */
    client_server.Protos.Person getPerson(int index);
    /**
     * <code>repeated .client_server.Person person = 1;</code>
     */
    int getPersonCount();
    /**
     * <code>repeated .client_server.Person person = 1;</code>
     */
    java.util.List<? extends client_server.Protos.PersonOrBuilder> 
        getPersonOrBuilderList();
    /**
     * <code>repeated .client_server.Person person = 1;</code>
     */
    client_server.Protos.PersonOrBuilder getPersonOrBuilder(
        int index);

    /**
     * <code>repeated .client_server.Chat chat = 2;</code>
     */
    java.util.List<client_server.Protos.Chat> 
        getChatList();
    /**
     * <code>repeated .client_server.Chat chat = 2;</code>
     */
    client_server.Protos.Chat getChat(int index);
    /**
     * <code>repeated .client_server.Chat chat = 2;</code>
     */
    int getChatCount();
    /**
     * <code>repeated .client_server.Chat chat = 2;</code>
     */
    java.util.List<? extends client_server.Protos.ChatOrBuilder> 
        getChatOrBuilderList();
    /**
     * <code>repeated .client_server.Chat chat = 2;</code>
     */
    client_server.Protos.ChatOrBuilder getChatOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code client_server.Sys}
   */
  public  static final class Sys extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:client_server.Sys)
      SysOrBuilder {
    // Use Sys.newBuilder() to construct.
    private Sys(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Sys() {
      person_ = java.util.Collections.emptyList();
      chat_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Sys(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                person_ = new java.util.ArrayList<client_server.Protos.Person>();
                mutable_bitField0_ |= 0x00000001;
              }
              person_.add(
                  input.readMessage(client_server.Protos.Person.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                chat_ = new java.util.ArrayList<client_server.Protos.Chat>();
                mutable_bitField0_ |= 0x00000002;
              }
              chat_.add(
                  input.readMessage(client_server.Protos.Chat.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = java.util.Collections.unmodifiableList(person_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          chat_ = java.util.Collections.unmodifiableList(chat_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return client_server.Protos.internal_static_client_server_Sys_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return client_server.Protos.internal_static_client_server_Sys_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              client_server.Protos.Sys.class, client_server.Protos.Sys.Builder.class);
    }

    public static final int PERSON_FIELD_NUMBER = 1;
    private java.util.List<client_server.Protos.Person> person_;
    /**
     * <code>repeated .client_server.Person person = 1;</code>
     */
    public java.util.List<client_server.Protos.Person> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .client_server.Person person = 1;</code>
     */
    public java.util.List<? extends client_server.Protos.PersonOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .client_server.Person person = 1;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .client_server.Person person = 1;</code>
     */
    public client_server.Protos.Person getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .client_server.Person person = 1;</code>
     */
    public client_server.Protos.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }

    public static final int CHAT_FIELD_NUMBER = 2;
    private java.util.List<client_server.Protos.Chat> chat_;
    /**
     * <code>repeated .client_server.Chat chat = 2;</code>
     */
    public java.util.List<client_server.Protos.Chat> getChatList() {
      return chat_;
    }
    /**
     * <code>repeated .client_server.Chat chat = 2;</code>
     */
    public java.util.List<? extends client_server.Protos.ChatOrBuilder> 
        getChatOrBuilderList() {
      return chat_;
    }
    /**
     * <code>repeated .client_server.Chat chat = 2;</code>
     */
    public int getChatCount() {
      return chat_.size();
    }
    /**
     * <code>repeated .client_server.Chat chat = 2;</code>
     */
    public client_server.Protos.Chat getChat(int index) {
      return chat_.get(index);
    }
    /**
     * <code>repeated .client_server.Chat chat = 2;</code>
     */
    public client_server.Protos.ChatOrBuilder getChatOrBuilder(
        int index) {
      return chat_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPersonCount(); i++) {
        if (!getPerson(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getChatCount(); i++) {
        if (!getChat(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(1, person_.get(i));
      }
      for (int i = 0; i < chat_.size(); i++) {
        output.writeMessage(2, chat_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_.get(i));
      }
      for (int i = 0; i < chat_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, chat_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof client_server.Protos.Sys)) {
        return super.equals(obj);
      }
      client_server.Protos.Sys other = (client_server.Protos.Sys) obj;

      boolean result = true;
      result = result && getPersonList()
          .equals(other.getPersonList());
      result = result && getChatList()
          .equals(other.getChatList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getPersonCount() > 0) {
        hash = (37 * hash) + PERSON_FIELD_NUMBER;
        hash = (53 * hash) + getPersonList().hashCode();
      }
      if (getChatCount() > 0) {
        hash = (37 * hash) + CHAT_FIELD_NUMBER;
        hash = (53 * hash) + getChatList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static client_server.Protos.Sys parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static client_server.Protos.Sys parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static client_server.Protos.Sys parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static client_server.Protos.Sys parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static client_server.Protos.Sys parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static client_server.Protos.Sys parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static client_server.Protos.Sys parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static client_server.Protos.Sys parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static client_server.Protos.Sys parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static client_server.Protos.Sys parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(client_server.Protos.Sys prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code client_server.Sys}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:client_server.Sys)
        client_server.Protos.SysOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return client_server.Protos.internal_static_client_server_Sys_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return client_server.Protos.internal_static_client_server_Sys_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                client_server.Protos.Sys.class, client_server.Protos.Sys.Builder.class);
      }

      // Construct using client_server.Protos.Sys.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
          getChatFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          personBuilder_.clear();
        }
        if (chatBuilder_ == null) {
          chat_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          chatBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return client_server.Protos.internal_static_client_server_Sys_descriptor;
      }

      public client_server.Protos.Sys getDefaultInstanceForType() {
        return client_server.Protos.Sys.getDefaultInstance();
      }

      public client_server.Protos.Sys build() {
        client_server.Protos.Sys result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public client_server.Protos.Sys buildPartial() {
        client_server.Protos.Sys result = new client_server.Protos.Sys(this);
        int from_bitField0_ = bitField0_;
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            person_ = java.util.Collections.unmodifiableList(person_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        if (chatBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            chat_ = java.util.Collections.unmodifiableList(chat_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.chat_ = chat_;
        } else {
          result.chat_ = chatBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof client_server.Protos.Sys) {
          return mergeFrom((client_server.Protos.Sys)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(client_server.Protos.Sys other) {
        if (other == client_server.Protos.Sys.getDefaultInstance()) return this;
        if (personBuilder_ == null) {
          if (!other.person_.isEmpty()) {
            if (person_.isEmpty()) {
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePersonIsMutable();
              person_.addAll(other.person_);
            }
            onChanged();
          }
        } else {
          if (!other.person_.isEmpty()) {
            if (personBuilder_.isEmpty()) {
              personBuilder_.dispose();
              personBuilder_ = null;
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
              personBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPersonFieldBuilder() : null;
            } else {
              personBuilder_.addAllMessages(other.person_);
            }
          }
        }
        if (chatBuilder_ == null) {
          if (!other.chat_.isEmpty()) {
            if (chat_.isEmpty()) {
              chat_ = other.chat_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureChatIsMutable();
              chat_.addAll(other.chat_);
            }
            onChanged();
          }
        } else {
          if (!other.chat_.isEmpty()) {
            if (chatBuilder_.isEmpty()) {
              chatBuilder_.dispose();
              chatBuilder_ = null;
              chat_ = other.chat_;
              bitField0_ = (bitField0_ & ~0x00000002);
              chatBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getChatFieldBuilder() : null;
            } else {
              chatBuilder_.addAllMessages(other.chat_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPersonCount(); i++) {
          if (!getPerson(i).isInitialized()) {
            return false;
          }
        }
        for (int i = 0; i < getChatCount(); i++) {
          if (!getChat(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        client_server.Protos.Sys parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (client_server.Protos.Sys) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<client_server.Protos.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = new java.util.ArrayList<client_server.Protos.Person>(person_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          client_server.Protos.Person, client_server.Protos.Person.Builder, client_server.Protos.PersonOrBuilder> personBuilder_;

      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public java.util.List<client_server.Protos.Person> getPersonList() {
        if (personBuilder_ == null) {
          return java.util.Collections.unmodifiableList(person_);
        } else {
          return personBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public int getPersonCount() {
        if (personBuilder_ == null) {
          return person_.size();
        } else {
          return personBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public client_server.Protos.Person getPerson(int index) {
        if (personBuilder_ == null) {
          return person_.get(index);
        } else {
          return personBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public Builder setPerson(
          int index, client_server.Protos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.set(index, value);
          onChanged();
        } else {
          personBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public Builder setPerson(
          int index, client_server.Protos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.set(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public Builder addPerson(client_server.Protos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(value);
          onChanged();
        } else {
          personBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public Builder addPerson(
          int index, client_server.Protos.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(index, value);
          onChanged();
        } else {
          personBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public Builder addPerson(
          client_server.Protos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public Builder addPerson(
          int index, client_server.Protos.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public Builder addAllPerson(
          java.lang.Iterable<? extends client_server.Protos.Person> values) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, person_);
          onChanged();
        } else {
          personBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public Builder removePerson(int index) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.remove(index);
          onChanged();
        } else {
          personBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public client_server.Protos.Person.Builder getPersonBuilder(
          int index) {
        return getPersonFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public client_server.Protos.PersonOrBuilder getPersonOrBuilder(
          int index) {
        if (personBuilder_ == null) {
          return person_.get(index);  } else {
          return personBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public java.util.List<? extends client_server.Protos.PersonOrBuilder> 
           getPersonOrBuilderList() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(person_);
        }
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public client_server.Protos.Person.Builder addPersonBuilder() {
        return getPersonFieldBuilder().addBuilder(
            client_server.Protos.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public client_server.Protos.Person.Builder addPersonBuilder(
          int index) {
        return getPersonFieldBuilder().addBuilder(
            index, client_server.Protos.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .client_server.Person person = 1;</code>
       */
      public java.util.List<client_server.Protos.Person.Builder> 
           getPersonBuilderList() {
        return getPersonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          client_server.Protos.Person, client_server.Protos.Person.Builder, client_server.Protos.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              client_server.Protos.Person, client_server.Protos.Person.Builder, client_server.Protos.PersonOrBuilder>(
                  person_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      private java.util.List<client_server.Protos.Chat> chat_ =
        java.util.Collections.emptyList();
      private void ensureChatIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          chat_ = new java.util.ArrayList<client_server.Protos.Chat>(chat_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          client_server.Protos.Chat, client_server.Protos.Chat.Builder, client_server.Protos.ChatOrBuilder> chatBuilder_;

      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public java.util.List<client_server.Protos.Chat> getChatList() {
        if (chatBuilder_ == null) {
          return java.util.Collections.unmodifiableList(chat_);
        } else {
          return chatBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public int getChatCount() {
        if (chatBuilder_ == null) {
          return chat_.size();
        } else {
          return chatBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public client_server.Protos.Chat getChat(int index) {
        if (chatBuilder_ == null) {
          return chat_.get(index);
        } else {
          return chatBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public Builder setChat(
          int index, client_server.Protos.Chat value) {
        if (chatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChatIsMutable();
          chat_.set(index, value);
          onChanged();
        } else {
          chatBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public Builder setChat(
          int index, client_server.Protos.Chat.Builder builderForValue) {
        if (chatBuilder_ == null) {
          ensureChatIsMutable();
          chat_.set(index, builderForValue.build());
          onChanged();
        } else {
          chatBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public Builder addChat(client_server.Protos.Chat value) {
        if (chatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChatIsMutable();
          chat_.add(value);
          onChanged();
        } else {
          chatBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public Builder addChat(
          int index, client_server.Protos.Chat value) {
        if (chatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChatIsMutable();
          chat_.add(index, value);
          onChanged();
        } else {
          chatBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public Builder addChat(
          client_server.Protos.Chat.Builder builderForValue) {
        if (chatBuilder_ == null) {
          ensureChatIsMutable();
          chat_.add(builderForValue.build());
          onChanged();
        } else {
          chatBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public Builder addChat(
          int index, client_server.Protos.Chat.Builder builderForValue) {
        if (chatBuilder_ == null) {
          ensureChatIsMutable();
          chat_.add(index, builderForValue.build());
          onChanged();
        } else {
          chatBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public Builder addAllChat(
          java.lang.Iterable<? extends client_server.Protos.Chat> values) {
        if (chatBuilder_ == null) {
          ensureChatIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, chat_);
          onChanged();
        } else {
          chatBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public Builder clearChat() {
        if (chatBuilder_ == null) {
          chat_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          chatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public Builder removeChat(int index) {
        if (chatBuilder_ == null) {
          ensureChatIsMutable();
          chat_.remove(index);
          onChanged();
        } else {
          chatBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public client_server.Protos.Chat.Builder getChatBuilder(
          int index) {
        return getChatFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public client_server.Protos.ChatOrBuilder getChatOrBuilder(
          int index) {
        if (chatBuilder_ == null) {
          return chat_.get(index);  } else {
          return chatBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public java.util.List<? extends client_server.Protos.ChatOrBuilder> 
           getChatOrBuilderList() {
        if (chatBuilder_ != null) {
          return chatBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(chat_);
        }
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public client_server.Protos.Chat.Builder addChatBuilder() {
        return getChatFieldBuilder().addBuilder(
            client_server.Protos.Chat.getDefaultInstance());
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public client_server.Protos.Chat.Builder addChatBuilder(
          int index) {
        return getChatFieldBuilder().addBuilder(
            index, client_server.Protos.Chat.getDefaultInstance());
      }
      /**
       * <code>repeated .client_server.Chat chat = 2;</code>
       */
      public java.util.List<client_server.Protos.Chat.Builder> 
           getChatBuilderList() {
        return getChatFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          client_server.Protos.Chat, client_server.Protos.Chat.Builder, client_server.Protos.ChatOrBuilder> 
          getChatFieldBuilder() {
        if (chatBuilder_ == null) {
          chatBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              client_server.Protos.Chat, client_server.Protos.Chat.Builder, client_server.Protos.ChatOrBuilder>(
                  chat_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          chat_ = null;
        }
        return chatBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:client_server.Sys)
    }

    // @@protoc_insertion_point(class_scope:client_server.Sys)
    private static final client_server.Protos.Sys DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new client_server.Protos.Sys();
    }

    public static client_server.Protos.Sys getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Sys>
        PARSER = new com.google.protobuf.AbstractParser<Sys>() {
      public Sys parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Sys(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Sys> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sys> getParserForType() {
      return PARSER;
    }

    public client_server.Protos.Sys getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:client_server.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string pass = 2;</code>
     */
    boolean hasPass();
    /**
     * <code>required string pass = 2;</code>
     */
    java.lang.String getPass();
    /**
     * <code>required string pass = 2;</code>
     */
    com.google.protobuf.ByteString
        getPassBytes();
  }
  /**
   * Protobuf type {@code client_server.Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:client_server.Person)
      PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      pass_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              pass_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return client_server.Protos.internal_static_client_server_Person_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return client_server.Protos.internal_static_client_server_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              client_server.Protos.Person.class, client_server.Protos.Person.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASS_FIELD_NUMBER = 2;
    private volatile java.lang.Object pass_;
    /**
     * <code>required string pass = 2;</code>
     */
    public boolean hasPass() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string pass = 2;</code>
     */
    public java.lang.String getPass() {
      java.lang.Object ref = pass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pass_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string pass = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPassBytes() {
      java.lang.Object ref = pass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPass()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, pass_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, pass_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof client_server.Protos.Person)) {
        return super.equals(obj);
      }
      client_server.Protos.Person other = (client_server.Protos.Person) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasPass() == other.hasPass());
      if (hasPass()) {
        result = result && getPass()
            .equals(other.getPass());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasPass()) {
        hash = (37 * hash) + PASS_FIELD_NUMBER;
        hash = (53 * hash) + getPass().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static client_server.Protos.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static client_server.Protos.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static client_server.Protos.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static client_server.Protos.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static client_server.Protos.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static client_server.Protos.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static client_server.Protos.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static client_server.Protos.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static client_server.Protos.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static client_server.Protos.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(client_server.Protos.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code client_server.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:client_server.Person)
        client_server.Protos.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return client_server.Protos.internal_static_client_server_Person_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return client_server.Protos.internal_static_client_server_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                client_server.Protos.Person.class, client_server.Protos.Person.Builder.class);
      }

      // Construct using client_server.Protos.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        pass_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return client_server.Protos.internal_static_client_server_Person_descriptor;
      }

      public client_server.Protos.Person getDefaultInstanceForType() {
        return client_server.Protos.Person.getDefaultInstance();
      }

      public client_server.Protos.Person build() {
        client_server.Protos.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public client_server.Protos.Person buildPartial() {
        client_server.Protos.Person result = new client_server.Protos.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pass_ = pass_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof client_server.Protos.Person) {
          return mergeFrom((client_server.Protos.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(client_server.Protos.Person other) {
        if (other == client_server.Protos.Person.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasPass()) {
          bitField0_ |= 0x00000002;
          pass_ = other.pass_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasPass()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        client_server.Protos.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (client_server.Protos.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pass_ = "";
      /**
       * <code>required string pass = 2;</code>
       */
      public boolean hasPass() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string pass = 2;</code>
       */
      public java.lang.String getPass() {
        java.lang.Object ref = pass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pass_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string pass = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPassBytes() {
        java.lang.Object ref = pass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string pass = 2;</code>
       */
      public Builder setPass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string pass = 2;</code>
       */
      public Builder clearPass() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pass_ = getDefaultInstance().getPass();
        onChanged();
        return this;
      }
      /**
       * <code>required string pass = 2;</code>
       */
      public Builder setPassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        pass_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:client_server.Person)
    }

    // @@protoc_insertion_point(class_scope:client_server.Person)
    private static final client_server.Protos.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new client_server.Protos.Person();
    }

    public static client_server.Protos.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public client_server.Protos.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:client_server.Chat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string note = 1;</code>
     */
    boolean hasNote();
    /**
     * <code>required string note = 1;</code>
     */
    java.lang.String getNote();
    /**
     * <code>required string note = 1;</code>
     */
    com.google.protobuf.ByteString
        getNoteBytes();

    /**
     * <code>required string person = 2;</code>
     */
    boolean hasPerson();
    /**
     * <code>required string person = 2;</code>
     */
    java.lang.String getPerson();
    /**
     * <code>required string person = 2;</code>
     */
    com.google.protobuf.ByteString
        getPersonBytes();
  }
  /**
   * Protobuf type {@code client_server.Chat}
   */
  public  static final class Chat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:client_server.Chat)
      ChatOrBuilder {
    // Use Chat.newBuilder() to construct.
    private Chat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Chat() {
      note_ = "";
      person_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Chat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              note_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              person_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return client_server.Protos.internal_static_client_server_Chat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return client_server.Protos.internal_static_client_server_Chat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              client_server.Protos.Chat.class, client_server.Protos.Chat.Builder.class);
    }

    private int bitField0_;
    public static final int NOTE_FIELD_NUMBER = 1;
    private volatile java.lang.Object note_;
    /**
     * <code>required string note = 1;</code>
     */
    public boolean hasNote() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string note = 1;</code>
     */
    public java.lang.String getNote() {
      java.lang.Object ref = note_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          note_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string note = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNoteBytes() {
      java.lang.Object ref = note_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        note_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PERSON_FIELD_NUMBER = 2;
    private volatile java.lang.Object person_;
    /**
     * <code>required string person = 2;</code>
     */
    public boolean hasPerson() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string person = 2;</code>
     */
    public java.lang.String getPerson() {
      java.lang.Object ref = person_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          person_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string person = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPersonBytes() {
      java.lang.Object ref = person_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        person_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNote()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPerson()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, note_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, person_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, note_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, person_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof client_server.Protos.Chat)) {
        return super.equals(obj);
      }
      client_server.Protos.Chat other = (client_server.Protos.Chat) obj;

      boolean result = true;
      result = result && (hasNote() == other.hasNote());
      if (hasNote()) {
        result = result && getNote()
            .equals(other.getNote());
      }
      result = result && (hasPerson() == other.hasPerson());
      if (hasPerson()) {
        result = result && getPerson()
            .equals(other.getPerson());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasNote()) {
        hash = (37 * hash) + NOTE_FIELD_NUMBER;
        hash = (53 * hash) + getNote().hashCode();
      }
      if (hasPerson()) {
        hash = (37 * hash) + PERSON_FIELD_NUMBER;
        hash = (53 * hash) + getPerson().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static client_server.Protos.Chat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static client_server.Protos.Chat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static client_server.Protos.Chat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static client_server.Protos.Chat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static client_server.Protos.Chat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static client_server.Protos.Chat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static client_server.Protos.Chat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static client_server.Protos.Chat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static client_server.Protos.Chat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static client_server.Protos.Chat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(client_server.Protos.Chat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code client_server.Chat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:client_server.Chat)
        client_server.Protos.ChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return client_server.Protos.internal_static_client_server_Chat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return client_server.Protos.internal_static_client_server_Chat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                client_server.Protos.Chat.class, client_server.Protos.Chat.Builder.class);
      }

      // Construct using client_server.Protos.Chat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        note_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        person_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return client_server.Protos.internal_static_client_server_Chat_descriptor;
      }

      public client_server.Protos.Chat getDefaultInstanceForType() {
        return client_server.Protos.Chat.getDefaultInstance();
      }

      public client_server.Protos.Chat build() {
        client_server.Protos.Chat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public client_server.Protos.Chat buildPartial() {
        client_server.Protos.Chat result = new client_server.Protos.Chat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.note_ = note_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.person_ = person_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof client_server.Protos.Chat) {
          return mergeFrom((client_server.Protos.Chat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(client_server.Protos.Chat other) {
        if (other == client_server.Protos.Chat.getDefaultInstance()) return this;
        if (other.hasNote()) {
          bitField0_ |= 0x00000001;
          note_ = other.note_;
          onChanged();
        }
        if (other.hasPerson()) {
          bitField0_ |= 0x00000002;
          person_ = other.person_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNote()) {
          return false;
        }
        if (!hasPerson()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        client_server.Protos.Chat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (client_server.Protos.Chat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object note_ = "";
      /**
       * <code>required string note = 1;</code>
       */
      public boolean hasNote() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string note = 1;</code>
       */
      public java.lang.String getNote() {
        java.lang.Object ref = note_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            note_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string note = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNoteBytes() {
        java.lang.Object ref = note_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          note_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string note = 1;</code>
       */
      public Builder setNote(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        note_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string note = 1;</code>
       */
      public Builder clearNote() {
        bitField0_ = (bitField0_ & ~0x00000001);
        note_ = getDefaultInstance().getNote();
        onChanged();
        return this;
      }
      /**
       * <code>required string note = 1;</code>
       */
      public Builder setNoteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        note_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object person_ = "";
      /**
       * <code>required string person = 2;</code>
       */
      public boolean hasPerson() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string person = 2;</code>
       */
      public java.lang.String getPerson() {
        java.lang.Object ref = person_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            person_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string person = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPersonBytes() {
        java.lang.Object ref = person_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          person_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string person = 2;</code>
       */
      public Builder setPerson(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        person_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string person = 2;</code>
       */
      public Builder clearPerson() {
        bitField0_ = (bitField0_ & ~0x00000002);
        person_ = getDefaultInstance().getPerson();
        onChanged();
        return this;
      }
      /**
       * <code>required string person = 2;</code>
       */
      public Builder setPersonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        person_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:client_server.Chat)
    }

    // @@protoc_insertion_point(class_scope:client_server.Chat)
    private static final client_server.Protos.Chat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new client_server.Protos.Chat();
    }

    public static client_server.Protos.Chat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Chat>
        PARSER = new com.google.protobuf.AbstractParser<Chat>() {
      public Chat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Chat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Chat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Chat> getParserForType() {
      return PARSER;
    }

    public client_server.Protos.Chat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_client_server_Sys_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_client_server_Sys_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_client_server_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_client_server_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_client_server_Chat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_client_server_Chat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032client_server/protos.proto\022\rclient_ser" +
      "ver\"O\n\003Sys\022%\n\006person\030\001 \003(\0132\025.client_serv" +
      "er.Person\022!\n\004chat\030\002 \003(\0132\023.client_server." +
      "Chat\"$\n\006Person\022\014\n\004name\030\001 \002(\t\022\014\n\004pass\030\002 \002" +
      "(\t\"$\n\004Chat\022\014\n\004note\030\001 \002(\t\022\016\n\006person\030\002 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_client_server_Sys_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_client_server_Sys_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_client_server_Sys_descriptor,
        new java.lang.String[] { "Person", "Chat", });
    internal_static_client_server_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_client_server_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_client_server_Person_descriptor,
        new java.lang.String[] { "Name", "Pass", });
    internal_static_client_server_Chat_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_client_server_Chat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_client_server_Chat_descriptor,
        new java.lang.String[] { "Note", "Person", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
